[package]
name = "opentelemetry-system-metrics"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { git="https://github.com/open-telemetry/opentelemetry-rust", features = ["rt-tokio", "metrics"] }
sysinfo = { git="https://github.com/haixuanTao/sysinfo" }
indexmap = "1.8"

