[package]
name = "opentelemetry-system-metrics"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "System metric export through Opentelemetry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version="0.17.0", features = ["rt-tokio", "metrics"] }
sysinfo = "0.24.5"
indexmap = "1.8"
